### PR TITLE
Tjmadonna/requests json fix

### PR DESCRIPTION
**Pull request by tjmadonna**
Fixed an issue while accessing JSON data. The return type from function `execute_opensearch_query` is a `urllib3.Response` type, which doesn't have a `get_json` function.

### CODE REVIEW

**Comment by yuanzhou** [comment]
@tjmadonna @maxsibilla we've been using that `get_json()` for over two years without issues with `/reindex-all`. Can we find out the root case?
Screenshot 2024-08-26 at 2 44 46 PM

**Comment by tjmadonna** [comment]
I'm guessing it was this change. The return type from `execute_query` is a Flask response while the return type from `execute_opensearch_query` is urllib3 response.

Screenshot 2024-08-26 at 4 16 09 PM

**Comment by yuanzhou** [comment]
@tjmadonna thanks, now I understand. FYI @kburke this appears to be introduced by your recent S3 enhancement work, no action is needed from you, the SenNet team noticed and already made the fix.

**Review by yuanzhou — APPROVED** [review]

**Comment by kburke** [comment]
Thanks for letting me know @yuanzhou.  I did not launch `reindex-all` during my work, and didn't think we would be migrating my stuff along until it could replace `reindex-all`. Halfway there, I guess...

**Pull request merged**
